all:
  children:
    rackspace_hosts:
      hosts:
        bootstrap_host:
          ansible_host: "{{ target_host }}"
          ansible_connection: ssh
          ansible_user: root
          ansible_ssh_private_key_file: "{{ target_ssh_key }}"
          ansible_ssh_extra_args: "-o IdentitiesOnly=yes"
      children:
        kubernetes:
          children:
            kubemasters:
              hosts:
                104.130.69.162:
                  ansible_connection: ssh
                  ansible_user: ansible
                  ansible_ssh_private_key_file: "{{ target_ssh_key }}"
                  ansible_ssh_extra_args: "-o IdentitiesOnly=yes"
            kubeworkers:
              hosts:
                104.130.69.163:
                  ansible_connection: ssh
                  ansible_user: ansible
                  ansible_ssh_private_key_file: "{{ target_ssh_key }}"
                  ansible_ssh_extra_args: "-o IdentitiesOnly=yes"
                166.78.116.37:
                  ansible_connection: ssh
                  ansible_user: ansible
                  ansible_ssh_private_key_file: "{{ target_ssh_key }}"
                  ansible_ssh_extra_args: "-o IdentitiesOnly=yes"
                104.130.216.50:
                  ansible_connection: ssh
                  ansible_user: ansible
                  ansible_ssh_private_key_file: "{{ target_ssh_key }}"
                  ansible_ssh_extra_args: "-o IdentitiesOnly=yes"
