all:
  children:
    rackspace_hosts:
      children:
        kubernetes:
          children:
            kubemasters:
              hosts:
                104.130.69.162:
                  ansible_connection: ssh
                  ansible_user: ansible
                  ansible_ssh_private_key_file: "{{ target_ssh_key }}"
                  ansible_ssh_extra_args: "-o IdentitiesOnly=yes"
            kubeworkers:
              hosts:
                104.130.69.163:
                  ansible_connection: ssh
                  ansible_user: ansible
                  ansible_ssh_private_key_file: "{{ target_ssh_key }}"
                  ansible_ssh_extra_args: "-o IdentitiesOnly=yes"
