all:
  hosts:
    rackspace_host:
      ansible_connection: ssh
      ansible_host: "{{ target_ip }}"
      ansible_user: "{{ target_ssh_user | default('ansible') }}"
      ansible_ssh_private_key_file: "{{ target_ssh_key }}"
