all:
  hosts:
    rackspacehost:
      ansible_connection: ssh
      ansible_host: "{{ target_host }}"
      ansible_user: root
      ansible_ssh_private_key_file: /Users/devon/.ssh/atat-rackspace-devon_rsa
      gather_facts: no
