all:
  children:
    bootstrap:
      hosts:
        bootstrap_host:
          ansible_host: "{{ target_host }}"
          ansible_connection: ssh
          ansible_user: root
          ansible_ssh_private_key_file: "{{ target_ssh_key }}"
          ansible_ssh_extra_args: "-o IdentitiesOnly=yes"
    rackspace:
      children:
        kubernetes:
          children:
            # kubemasters:
            #   hosts:
            #     192.237.172.125:
            #       ansible_connection: ssh
            #       ansible_user: ansible
            #       ansible_ssh_private_key_file: "{{ target_ssh_key }}"
            #       ansible_ssh_extra_args: "-o IdentitiesOnly=yes"
            kubeworkers:
              hosts:
                # 23.253.207.116:
                #   ansible_connection: ssh
                #   ansible_user: ansible
                #   ansible_ssh_private_key_file: "{{ target_ssh_key }}"
                #   ansible_ssh_extra_args: "-o IdentitiesOnly=yes"
                23.253.164.211:
                  ansible_connection: ssh
                  ansible_user: ansible
                  ansible_ssh_private_key_file: "{{ target_ssh_key }}"
                  ansible_ssh_extra_args: "-o IdentitiesOnly=yes"
                # 23.253.205.161:
                #   ansible_connection: ssh
                #   ansible_user: ansible
                #   ansible_ssh_private_key_file: "{{ target_ssh_key }}"
                #   ansible_ssh_extra_args: "-o IdentitiesOnly=yes"
