---
- name: Install docker requisites
  apt: name=apt-transport-https,ca-certificates,software-properties-common

- name: Add Docker repo key
  apt_key: url="https://download.docker.com/linux/debian/gpg"
  ignore_errors: yes
  register: add_docker_repo

- name: Add Docker repo key (python 2.7.9 or older)
  shell: curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -qq - >/dev/null
  when: add_docker_repo|failed

- name: Add docker repo
  apt_repository: repo='deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable' state=present update_cache=yes
  when: ansible_distribution != "Ubuntu"

- name: Add docker repo
  apt_repository: repo='deb https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} edge' state=present update_cache=yes
  when: ansible_distribution == "Ubuntu"

- name: Install docker
  apt: name="docker-ce" state=installed force=yes
  when: ansible_distribution == "Ubuntu"

- name: Add repo key
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    state: present

- name: Add kubernetes repo
  apt_repository: repo='deb http://apt.kubernetes.io/ kubernetes-xenial main' state=present update_cache=yes

- name: Install kubernetes packages
  apt: name=kubelet,kubeadm,kubectl state=installed
