---
- name: Wait for Kube master
  wait_for:
    path: /etc/profile.d/kube.sh
  delegate_to: "{{kube_server}}"

- name: Add node to kube cluster
  command: kubeadm join --token {{kube_token}} {{kube_server}}:6443 --discovery-token-unsafe-skip-ca-verification creates=/etc/kubernetes/kubelet.conf
