---

kubeadm_cgroup_driver: cgroupfs
kubeadm_cluster_dns: "10.96.0.10"
kubeadm_cluster_domain: "cluster.local"

kubeadm_proxy_env:
  ansible_user_id: "{{ ansible_user_id }}"
  http_proxy: "{{ lookup('env', 'http_proxy') }}"
  https_proxy: "{{ lookup('env', 'https_proxy') }}"
  socks_proxy: "{{ lookup('env', 'socks_proxy') }}"
