---

- name: Set cluster DNS
  lineinfile:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: '^Environment="KUBELET_DNS_ARGS='
    line: "Environment=\"KUBELET_DNS_ARGS=--cluster-dns={{ kubeadm_cluster_dns }} --cluster-domain={{ kubeadm_cluster_domain }}\""
  notify:
    - reload kubelet
  become: yes

- name: Unset fail-swap-on
  lineinfile:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: '^Environment="KUBELET_EXTRA_ARGS='
    line: "Environment=\"KUBELET_EXTRA_ARGS=--fail-swap-on=false\""
  notify:
    - reload kubelet
  become: yes

- name: Set cgroup driver
  lineinfile:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: '^Environment="KUBELET_CGROUP_ARGS='
    line: "Environment=\"KUBELET_CGROUP_ARGS=--cgroup-driver={{ kubeadm_cgroup_driver }}\""
  notify:
    - reload kubelet
  become: yes

- name: Enable Kubelet
  service:
    name: kubelet
    enabled: yes
  become: yes
