---

- name: Disable SELinux
  selinux:
    state: disabled
  become: yes

- name: Add Kubernetes Repo
  copy: src=kubernetes.repo dest=/etc/yum.repos.d/kubernetes.repo
  become: yes
  when: ansible_os_family == 'RedHat'

- name: Install GPG keys, workaround for Ansible issue 20711
  command: yum -q makecache -y --disablerepo=* --enablerepo=kubernetes
  environment: "{{ kubeadm_proxy_env }}"
  become: yes

- name: Install Kubeadm
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - kubeadm
    - kubelet
    - kubernetes-cni
  environment: "{{ kubeadm_proxy_env }}"
  become: yes
